spring.application.name=nodes-crud

spring.datasource.url=jdbc:postgresql://localhost:5431/nodes_crud
spring.datasource.username=postgres
spring.datasource.password=chiquis200
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jackson.deserialization.fail-on-null-for-primitives = false
