CREATE TABLE IF NOT EXISTS node (
    node_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    input VARCHAR(255) NOT NULL,
    output VARCHAR(255) NOT NULL,
    node_type VARCHAR(255) NOT NULL,
    position_x REAL NOT NULL,
    position_y REAL NOT NULL,
    sequence INTEGER NOT NULL,
    is_active BOOLEAN NOT NULL,
    create_timestamp TIMESTAMP WITH TIME ZONE,
    update_timestamp TIMESTAMP WITH TIME ZONE
);
